controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 400  # Hz

    joint_trajectory_controller:
     type: joint_trajectory_controller/JointTrajectoryController

    diff_cont:
     type: diff_drive_controller/DiffDriveController

    joint_broad:
     type: joint_state_broadcaster/JointStateBroadcaster
    

joint_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5


diff_cont:
 ros__parameters:
   use_sim_time: true
   update_rate: 400
   base_frame_id: base_link
   use_stamped_vel: false

   left_wheel_names: ['left_wheel_joint']
   right_wheel_names: ['right_wheel_joint']

   wheel_separation: 0.316
   wheel_radius: 0.051